### ISSUE TITLE
Error: Out of range

### ISSUE THREAD

**Issue by ingria** [ton-community/disassembler#1]
Sometimes there's an "Out of range" error when disassembling contracts, e. g. Ef8zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM0vF

```javascript
import { fromCode } from 'tvm-disassembler';
import { Cell } from 'ton';

const contract = await provider.getAddressInfo('Ef8zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM0vF');

const codeBytes = Buffer.from(contract.code, 'base64');

const cell = Cell.fromBoc(codeBytes)[0];
const decompiled = await fromCode(cell);
```

```
Error: Out of range
    at BitStringReader.getBit (node_modules/ton/dist/boc/BitStringReader.js:123:19)
    at BitStringReader.readBit (node_modules/ton/dist/boc/BitStringReader.js:71:22)
    at Slice.readBit (node_modules/ton/dist/boc/Slice.js:27:30)
    at fetchSubslice (node_modules/tvm-disassembler/dist/codepages/cp0.generated.js:10:37)
    at node_modules/tvm-disassembler/dist/codepages/cp0.generated.js:321:20
    at decompile (node_modules/tvm-disassembler/dist/disassembler.js:51:20)
    at node_modules/tvm-disassembler/dist/codepages/cp0.generated.js:317:48
    at decompile (node_modules/tvm-disassembler/dist/disassembler.js:51:20)
    at node_modules/tvm-disassembler/dist/codepages/cp0.generated.js:823:48
    at decompile (node_modules/tvm-disassembler/dist/disassembler.js:51:20)
```

**Comment by dvlkv** [comment]
Thank you for your report. Fixed by [this](https://github.com/ton-foundation/disassembler/commit/55de300a371e716e4cb39919b26365850b5ddb14) commit. Published v1.2.1
